import mongoose from "mongoose";

const medidasCrecimientoSchema = mongoose.Schema({
  CODE: Number,
  Centro: Number,
  codigooriginal: Number,
  estadovital: Number,
  muerteprimerano: Number,
  ANOCAT: Number,
  nivelmama: Number,
  nivelpapa: Number,
  embarazodeseado: Number,
  edadmama: Number,
  pesomama: Number,
  tallamama: Number,
  pesopapa: Number,
  tallapapa: Number,
  Embarazomultiple: Number,
  numerocontrolprenatal: Number,
  pesoalnacer: Number,
  tallaalnacer: Number,
  sexo: Number,
  pcalnacer: Number,
  edadgestacional2: Number,
  edadgestacional: Number,
  classificacionlubchenco: Number,
  TotalDiasHospitalizacion: Number,
  toxemia: Number,
  UCI: Number,
  cesarea: Number,
  primipara: Number,
  trimestre: Number,
  VAR00002: Number,
  oftalmologiafinal: Number,
  ROP: Number,
  resoptometria: Number,
  audiometria: Number,
  edadalaentrada: Number,
  pesoalaentrada: Number,
  tallaalaentrada: Number,
  PCalaentrada: Number,
  edadgestacionalalaentrada: Number,
  edadgestacionalalaentrada2: Number,
  PesosalidaPC: Number,
  edadsalidaPC: Number,
  edadgestasalPC: Number,
  Infanib3m: Number,
  Infanib6m: Number,
  Infanib9m: Number,
  Infanib12m: Number,
  CD6: Number,
  CD12: Number,
  mes40: Number,
  mes3: Number,
  mes6: Number,
  mes9: Number,
  mes12: Number,
  alisalida: Number,
  Indexnutricion40sem: Number,
  indexnutricion12meses: Number,
  oxigenoentrada: Number,
  percapitasalariominimo: Number,
  RCIUpesoFenton: Number,
  RCIUtalla: Number,
  RCIUPC: Number,
  RCIUpesoFentonentrada: Number,
  RCIUtallaentrada: Number,
  RCIUPCentrada: Number,
  RCIUfentonpesotalla: Number,
  RCIUfentonpesotallaPC: Number,
  CD66: Number,
  CD122: Number,
  tipoRCIU: Number,
  tipoRCIU2: Number,
  Nutpcwho: {
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
  },
  pc: {
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
    error: Boolean,
    sem33: Number,
    outlier: Boolean,
  },
  alimentacion: {
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
  },
  talla: {
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
    error: Boolean,
    sem33: Number,
    outlier: Boolean,
  },
  peso: {
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
    error: Boolean,
    sem33: Number,
    outlier: Boolean,
  },
  Nutpesowho: {
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
  },
  Nuttallawho: {
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
  },
  pesoalnacer_Normalizado: Number,
  peso_normalizado: {
    sem33: Number,
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
  },
  talla_normalizado: {
    sem33: Number,
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
  },
  pc_normalizado: {
    sem33: Number,
    sem40: Number,
    mes3: Number,
    mes6: Number,
    mes9: Number,
    mes12: Number,
  },
  pesoalaentrada_Normalizado: Number,
  fechaCreacion: Date,
  neurologia: {
    error: Boolean,
  },
});

const medidasCrecimiento = mongoose.model(
  "medidasCrecimiento",
  medidasCrecimientoSchema,
  "medidas_crecimiento"
);

export default medidasCrecimiento;
